apiVersion: v1
kind: Service
metadata:
  name: keras-service
  labels:
    app: keras
spec:
  type: NodePort
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30100
    protocol: TCP
    name: jupyter
  - port: 6006
    targetPort: 6006
    nodePort: 30200
    protocol: TCP
    name: tensorboard
  selector:
    app: keras